// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWP391_BL3W.Database;

#nullable disable

namespace SWP391_BL3W.Migrations
{
    [DbContext(typeof(SWPContext))]
    [Migration("20240416055327_updatedatebase")]
    partial class updatedatebase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SWP391_BL3W.Database.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryBlogID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryBlogID");

                    b.HasIndex("UserId");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Ấm siêu tốc"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Bếp điện từ"
                        });
                });

            modelBuilder.Entity("SWP391_BL3W.Database.CategoryBlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryBlog");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("AddressCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("statusMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.OrderDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("ExpiredWarranty")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarrantyPeriod")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.ProductsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetail");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Customer"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("SWP391_BL3W.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "HCM",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2024, 4, 16, 12, 53, 26, 786, DateTimeKind.Local).AddTicks(4676),
                            Email = "admin@gmail.com",
                            Gender = "Male",
                            Name = "admin",
                            Password = "12345",
                            RoleId = 1,
                            phone = "0321456789",
                            status = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "HCM",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2002, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer@gmail.com",
                            Gender = "Male",
                            Name = "Custommer",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0501255079",
                            status = true
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ho Chi Minh City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1999, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jennifer.nguyen@gmail.com",
                            Gender = "Female",
                            Name = "Jennifer Nguyen",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0987654321",
                            status = true
                        },
                        new
                        {
                            Id = 4,
                            Address = "HCMC, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1995, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.tran@gmail.com",
                            Gender = "Male",
                            Name = "David Tran",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0901234567",
                            status = true
                        },
                        new
                        {
                            Id = 5,
                            Address = "District 3, HCMC",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1999, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jessica.le@gmail.com",
                            Gender = "Female",
                            Name = "Jessica Le",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0975123456",
                            status = true
                        },
                        new
                        {
                            Id = 6,
                            Address = "Tan Binh District, HCM",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1988, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kevin.vo@gmail.com",
                            Gender = "Male",
                            Name = "Kevin Vo",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0943216789",
                            status = true
                        },
                        new
                        {
                            Id = 7,
                            Address = "Phu Nhuan District, HCMC",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1992, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amanda.ho@gmail.com",
                            Gender = "Female",
                            Name = "Amanda Ho",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0912345678",
                            status = true
                        },
                        new
                        {
                            Id = 8,
                            Address = "District 1, HCM",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1985, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.nguyen@gmail.com",
                            Gender = "Male",
                            Name = "Alex Nguyen",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0987654321",
                            status = true
                        },
                        new
                        {
                            Id = 9,
                            Address = "Khanh Hoa, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2003, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nkhuong038424@gmail.com",
                            Gender = "Male",
                            Name = "David Khương",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0905022946",
                            status = true
                        },
                        new
                        {
                            Id = 10,
                            Address = "Quang Ngai, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2003, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khoatony3705@gmail.com",
                            Gender = "Male",
                            Name = "Tony Khoa",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0987657456",
                            status = true
                        },
                        new
                        {
                            Id = 11,
                            Address = "Binh Thanh District, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1997, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michelle.pham@gmail.com",
                            Gender = "Female",
                            Name = "Michelle Pham",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0965432187",
                            status = true
                        },
                        new
                        {
                            Id = 12,
                            Address = "Da nang City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1983, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jason.hoang@gmail.com",
                            Gender = "Male",
                            Name = "Jason Hoang",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0934567890",
                            status = true
                        },
                        new
                        {
                            Id = 13,
                            Address = "Tan Phu District, HCMC",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1991, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "stephanie.truong@gmail.com",
                            Gender = "Female",
                            Name = "Stephanie Truong",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0908765432",
                            status = true
                        },
                        new
                        {
                            Id = 14,
                            Address = "Vinh City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1997, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bray.nguyen@gmail.com",
                            Gender = "Male",
                            Name = "Bray Nguyen",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0976543210",
                            status = true
                        },
                        new
                        {
                            Id = 15,
                            Address = "Ho Chi Minh City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1989, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jonny.dang@gmail.com",
                            Gender = "Male",
                            Name = "Jonny Dang",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0965432109",
                            status = true
                        },
                        new
                        {
                            Id = 16,
                            Address = "Binh Tan District, HCM",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1975, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adam.huynh@gmail.com",
                            Gender = "Male",
                            Name = "Adam Huynh",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0912345678",
                            status = true
                        },
                        new
                        {
                            Id = 17,
                            Address = "District 4, HCM",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1993, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "derek.nguyen@gmail.com",
                            Gender = "Male",
                            Name = "Derek Nguyen",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0943216789",
                            status = true
                        },
                        new
                        {
                            Id = 18,
                            Address = "Ho Chi Minh City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1992, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace.nguyen@gmail.com",
                            Gender = "Female",
                            Name = "Grace Nguyen",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0912345678",
                            status = true
                        },
                        new
                        {
                            Id = 19,
                            Address = "District 2, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1985, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "henry.tran@gmail.com",
                            Gender = "Male",
                            Name = "Henry Tran",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0945678901",
                            status = true
                        },
                        new
                        {
                            Id = 20,
                            Address = "Binh Chanh District, HCM",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1996, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jacky.nguyen@gmail.com",
                            Gender = "Male",
                            Name = "Jacky Nguyen",
                            Password = "12345",
                            RoleId = 2,
                            phone = "0976543210",
                            status = true
                        },
                        new
                        {
                            Id = 21,
                            Address = "Nha Trang City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2003, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.khuong@gmail.com",
                            Gender = "Male",
                            Name = "Admin Khuong",
                            Password = "12345",
                            RoleId = 1,
                            phone = "095335780",
                            status = true
                        },
                        new
                        {
                            Id = 22,
                            Address = "Binh Duong, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2003, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.khoa@gmail.com",
                            Gender = "Male",
                            Name = "Admin Khoa",
                            Password = "12345",
                            RoleId = 1,
                            phone = "0953354430",
                            status = true
                        },
                        new
                        {
                            Id = 23,
                            Address = "HCM City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2002, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.khoi@gmail.com",
                            Gender = "Male",
                            Name = "Admin Khoi",
                            Password = "12345",
                            RoleId = 1,
                            phone = "0953353409",
                            status = true
                        },
                        new
                        {
                            Id = 24,
                            Address = "HCM City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(1993, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.Truong@gmail.com",
                            Gender = "Male",
                            Name = "Staff Truong",
                            Password = "12345",
                            RoleId = 3,
                            phone = "0501370820",
                            status = true
                        },
                        new
                        {
                            Id = 25,
                            Address = "HCM City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2002, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.quynh@gmail.com",
                            Gender = "Female",
                            Name = "Staff Quynh",
                            Password = "12345",
                            RoleId = 3,
                            phone = "0502360820",
                            status = true
                        },
                        new
                        {
                            Id = 26,
                            Address = "HCM City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2002, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.anh@gmail.com",
                            Gender = "Female",
                            Name = "Staff Anh",
                            Password = "12345",
                            RoleId = 3,
                            phone = "0502360730",
                            status = true
                        },
                        new
                        {
                            Id = 27,
                            Address = "HCM City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2002, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.duc@gmail.com",
                            Gender = "Male",
                            Name = "Staff Duc",
                            Password = "12345",
                            RoleId = 3,
                            phone = "0502366423",
                            status = true
                        },
                        new
                        {
                            Id = 28,
                            Address = "HCM City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2003, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.Dang@gmail.com",
                            Gender = "Male",
                            Name = "Staff Dang",
                            Password = "12345",
                            RoleId = 3,
                            phone = "0502360830",
                            status = true
                        },
                        new
                        {
                            Id = 29,
                            Address = "HCM City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2002, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.Nhan@gmail.com",
                            Gender = "Male",
                            Name = "Staff Nhan",
                            Password = "12345",
                            RoleId = 3,
                            phone = "0502360831",
                            status = true
                        },
                        new
                        {
                            Id = 30,
                            Address = "HCM City, Vietnam",
                            AvatarUrl = "https://inkythuatso.com/uploads/thumbnails/800/2023/03/9-anh-dai-dien-trang-inkythuatso-03-15-27-03.jpg",
                            DateOfBirth = new DateTime(2002, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin.Phu@gmail.com",
                            Gender = "Male",
                            Name = "Staff Phu",
                            Password = "12345",
                            RoleId = 3,
                            phone = "0703298295",
                            status = true
                        });
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Blog", b =>
                {
                    b.HasOne("SWP391_BL3W.Database.CategoryBlog", "CategoryBlog")
                        .WithMany("blogs")
                        .HasForeignKey("CategoryBlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_BL3W.Database.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryBlog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Cart", b =>
                {
                    b.HasOne("SWP391_BL3W.Database.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_BL3W.Database.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Images", b =>
                {
                    b.HasOne("SWP391_BL3W.Database.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Order", b =>
                {
                    b.HasOne("SWP391_BL3W.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.OrderDetail", b =>
                {
                    b.HasOne("SWP391_BL3W.Database.Order", "Order")
                        .WithMany("OrdersDetail")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_BL3W.Database.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Product", b =>
                {
                    b.HasOne("SWP391_BL3W.Database.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.ProductsDetail", b =>
                {
                    b.HasOne("SWP391_BL3W.Database.Product", "Product")
                        .WithMany("Details")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Review", b =>
                {
                    b.HasOne("SWP391_BL3W.Database.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_BL3W.Database.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.User", b =>
                {
                    b.HasOne("SWP391_BL3W.Database.Role", "Role")
                        .WithMany("users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.CategoryBlog", b =>
                {
                    b.Navigation("blogs");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Order", b =>
                {
                    b.Navigation("OrdersDetail");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Details");

                    b.Navigation("Images");

                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.Role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("SWP391_BL3W.Database.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Carts");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
